version: "3.9"
services:
  ### Nombre que tendrá el contenedor
  chanchito:
  ## ruta
    build: .
    ports:
    ## puerto SO: puerto Dock
      - "3000:3000"
      ## Nombre de contenedor que queremos mapear 
    links:
      - mongous
  mongous:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=PapiJofre
      - MONGO_INITDB_ROOT_PASSWORD=password

